# Generated by Django 6.0.3 on 2026-03-10 15:06

import django.utils.timezone
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='compensation_events/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompensationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('clause', models.CharField(choices=[('60.1(1)', '60.1(1) — PM instruction to change Works Info'), ('60.1(2)', '60.1(2) — PM does not reply to communication'), ('60.1(3)', '60.1(3) — PM instruction to stop or not start work'), ('60.1(4)', '60.1(4) — PM instruction to change Key Date'), ('60.1(5)', '60.1(5) — PM or Supervisor failure'), ('60.1(6)', '60.1(6) — PM does not accept work'), ('60.1(7)', '60.1(7) — Uncollected object'), ('60.1(8)', '60.1(8) — Physical conditions'), ('60.1(9)', '60.1(9) — Adverse weather'), ('60.1(10)', '60.1(10) — Employer risk event'), ('60.1(11)', '60.1(11) — Test or inspection causes delay'), ('60.1(12)', '60.1(12) — Employer does not provide'), ('60.1(13)', '60.1(13) — Breach by Employer'), ('60.1(14)', '60.1(14) — Preventive measures'), ('other', 'Other')], default='60.1(1)', max_length=20)),
                ('description', models.TextField(help_text='Description of the compensation event')),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', django_fsm.FSMField(default='notified', max_length=50, protected=True)),
                ('pm_instruction_date', models.DateTimeField(blank=True, null=True)),
                ('pm_reply', models.TextField(blank=True)),
                ('pm_accepted', models.BooleanField(blank=True, null=True)),
                ('quotation_submitted_date', models.DateTimeField(blank=True, null=True)),
                ('quotation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quotation_time_extension', models.IntegerField(blank=True, help_text='Time extension in days', null=True)),
                ('quotation_detail', models.TextField(blank=True)),
                ('implemented_date', models.DateTimeField(blank=True, null=True)),
                ('implemented_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('implemented_time_extension', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compensation Event',
                'verbose_name_plural': 'Compensation Events',
                'ordering': ['-notification_date'],
            },
        ),
    ]
