# Generated by Django 6.0.3 on 2026-03-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(help_text='Contract reference number', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('tender', 'Tender'), ('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('contract_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracted_projects', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('not_accepted', 'Not Accepted'), ('revised', 'Revised')], default='submitted', max_length=20)),
                ('pm_response', models.TextField(blank=True)),
                ('programme_file', models.FileField(blank=True, null=True, upload_to='programmes/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_programmes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='projects.project')),
            ],
            options={
                'ordering': ['-revision'],
                'unique_together': {('project', 'revision')},
            },
        ),
    ]
