# Generated by Django 6.0.3 on 2026-03-12 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contractororganisation_user_contractor_org'),
        ('projects', '0002_project_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor_representative',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'contractor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_projects', to=settings.AUTH_USER_MODEL, verbose_name="Contractor's Representative"),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.contractororganisation', verbose_name='Contractor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
    ]
