# Generated by Django 6.0.3 on 2026-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_contractdata_siteaccessdate_contractsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdata',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='law_of_contract',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='opt_y2',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='opt_y3',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='site_boundaries',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='tribunal',
        ),
        migrations.RemoveField(
            model_name='contractdata',
            name='works_information_ref',
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='currency',
            field=models.CharField(blank=True, default='HKD', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='employer_name',
            field=models.CharField(blank=True, help_text='NEC4 term. Referred to as "the Employer" in NEC3.', max_length=255, verbose_name='The Client'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='nec_version',
            field=models.CharField(blank=True, default='NEC4 ECC Hong Kong Edition (July 2023)', help_text='e.g. NEC4 ECC Hong Kong Edition (July 2023), NEC3 ECC (April 2013)', max_length=50, verbose_name='NEC Version'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='opt_w1',
            field=models.BooleanField(default=False, verbose_name='W1 – Dispute resolution (adjudication / arbitration — HK applicable)'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='opt_w2',
            field=models.BooleanField(default=False, verbose_name='W2 – Dispute resolution (UK HGCRA only — not applicable in HK)'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='opt_x11',
            field=models.BooleanField(default=False, verbose_name='X11 – Termination by the Client'),
        ),
    ]
