# Generated by Django 6.0.3 on 2026-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_replace_pm_supervisor_with_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ce_reference_prefix',
            field=models.CharField(default='CNCE-', help_text='Prefix for auto-generated Compensation Event reference numbers (e.g. CNCE-).', max_length=20, verbose_name='CE Reference Prefix'),
        ),
        migrations.AddField(
            model_name='project',
            name='ew_reference_prefix',
            field=models.CharField(default='CNEW-', help_text='Prefix for auto-generated Early Warning reference numbers (e.g. CNEW-).', max_length=20, verbose_name='EW Reference Prefix'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='advance_payment_amount',
            field=models.TextField(blank=True, help_text='Amount or formula, e.g. "lesser of 2% of tendered Prices or HKD500,000"', verbose_name='Advance Payment Amount'),
        ),
    ]
