# Generated by Django 6.0.3 on 2026-03-10 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('communication_type', models.CharField(choices=[('ce_notification', 'CE Notification (Cl.61.3)'), ('early_warning', 'Early Warning (Cl.15)'), ('pm_instruction', 'PM Instruction (Cl.14)'), ('programme_submission', 'Programme Submission (Cl.31)'), ('programme_acceptance', 'Programme Acceptance (Cl.31)'), ('payment_notice', 'Payment Notice (Cl.51)'), ('general', 'General Communication')], max_length=30)),
                ('direction', models.CharField(choices=[('pm_to_contractor', 'PM → Contractor'), ('contractor_to_pm', 'Contractor → PM'), ('contractor_to_supervisor', 'Contractor → Supervisor'), ('supervisor_to_contractor', 'Supervisor → Contractor')], max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communications/attachments/')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications Log',
                'ordering': ['-sent_date'],
            },
        ),
    ]
