# Generated by Django 6.0.3 on 2026-03-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('registration_no', models.CharField(blank=True, max_length=100, verbose_name='Company / Registration No.')),
                ('address', models.TextField(blank=True, verbose_name='Registered Address')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Contact Phone')),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contractor Organisation',
                'verbose_name_plural': 'Contractor Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='contractor_org',
            field=models.ForeignKey(blank=True, help_text='Assign contractor-role users to their company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.contractororganisation', verbose_name='Contractor Company'),
        ),
    ]
