# Generated by Django 6.0.3 on 2026-03-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, help_text='Auto-generated EW reference', max_length=50)),
                ('raised_by_party', models.CharField(choices=[('contractor', 'Contractor'), ('pm', 'Project Manager')], max_length=20)),
                ('description', models.TextField(help_text='Describe the matter that could affect cost, time, or quality')),
                ('potential_impact', models.TextField(help_text='Potential impact on the project')),
                ('mitigation', models.TextField(blank=True, help_text='Proposed mitigation actions')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('actioned', 'Actioned'), ('closed', 'Closed')], default='open', max_length=20)),
                ('risk_reduction_meeting_date', models.DateField(blank=True, null=True)),
                ('risk_reduction_meeting_notes', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_warnings', to='projects.project')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_early_warnings', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_early_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Early Warning',
                'verbose_name_plural': 'Early Warning Register',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyWarningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='early_warnings/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('early_warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='early_warnings.earlywarning')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
