# Generated by Django 6.0.3 on 2026-03-10 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation_events', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('people', 'People'), ('plant', 'Plant & Equipment'), ('materials', 'Materials'), ('subcontractor', 'Subcontractor'), ('charges', 'Charges'), ('manufacture', 'Manufacture & Fabrication')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('cost_date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='financial/receipts/')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_costs', to=settings.AUTH_USER_MODEL)),
                ('linked_ce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defined_costs', to='compensation_events.compensationevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defined_costs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Defined Cost',
                'verbose_name_plural': 'Defined Costs',
                'ordering': ['-cost_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.PositiveIntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pm_assessed', 'PM Assessed'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_certificates', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pm_assessed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pm_assessment_date', models.DateField(blank=True, null=True)),
                ('pm_notes', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_certificate', models.FileField(blank=True, null=True, upload_to='financial/certificates/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Application',
                'verbose_name_plural': 'Payment Applications',
                'ordering': ['-application_number'],
                'unique_together': {('project', 'application_number')},
            },
        ),
    ]
